version: '3.4'

services:
  db:
    container_name: db
    restart: unless-stopped
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - 8001:5432
    networks:
      strapi:
        ipv4_address: 172.20.0.10

  strapi:
    depends_on:
      - db
    container_name: strapi
    restart: unless-stopped
    build:
      context: ./store-backend
    env_file: .env
    command: npm run develop
    ports:
      - 1337:1337
    volumes:
      - ./strapi-backend:/opt/app
    networks:
      strapi:
        ipv4_address: 172.20.0.12
  
  nextjs:
    depends_on:
      - strapi
    container_name: nextjs
    environment:
      - API_LINK=http://strapi:1337
      - SECRET_REVALIDATE_KEY=secret_revalidate_key
      - NEXT_PUBLIC_CONTACT_FORM=xyyvzkqg
    build: ./store-frontend
    ports:
      - 3000:3000
    volumes:
      - ./nextjs-frontend:/app
    networks:
      strapi:
        ipv4_address: 172.20.0.14

volumes:
  strapi-data:

networks:
  strapi:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.1/24"
